name: Action-Test

on:
  schedule:
    - cron: "1 * * * *"
  # push:
  #   branches:
  #     - main
  # workflow_dispatch:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout...
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Run build task
        run: CI=false npm run build --if-present
