name: Action-Test


on:
  schedule:
    - cron: "34 10 * * *"
  # push:
  #   branches:
  #     - main
  # workflow_dispatch:
  #   branches:
  #     - main

jobs:
  version_update:
    #if: "contains(github.event.head_commit.message, '#prerelease')"
    runs-on: ubuntu-latest
    name: Version Update
    steps:
      - name: Checkout...
        uses: actions/checkout@v3

      - name: Version update
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: './'

  build:
    #if: "contains(github.event.head_commit.message, '#prerelease')"
    #needs: version_update
    runs-on: ubuntu-latest
    name: Build

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout...
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Run build task
        run: CI=false npm run build --if-present
