#maybe the prob was not using "/"
name: testing Again

on:
  schedule:
    - cron: "40 12 * * *"    #6:10pm
    - cron: "10 13 * * *"    #6:40pm
  # push:
  #   branches:
  #     - main
  # workflow_dispatch:
  #   branches:
  #     - main

jobs:
  install-dep:
    runs-on: ubuntu-latest
    name: Run

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout...
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci
